apiVersion: v1
kind: Secret
metadata:
  name: news-analytics-secrets
  namespace: news-analytics
type: Opaque
stringData:
  NEWSAPI_KEY: "your_newsapi_key_here"
  POSTGRES_PASSWORD: "newspass"
  MONGO_URI: "mongodb://mongo-service:27017"
